name: Docker build and publish

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: f4fhh/sdrplay_rsptcp
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
